const koa = require('koa')
const static = require('koa-static')
const path = require('path')
const app = new koa()
const router = require('./src/router_o/my_router')
app.use(static(path.join(__dirname,'static')))
app.use(router.routes())
app.use(router.allowedMethods({}))
app.listen(3000,()=>{
    console.log('application started on port: 3000')
})